name: vllm

# ON MULTI-GPU
# ============
# this is currently not managed well.
# if you wish to change the number of devices (in my local, home machine case,
# usually single or dual GPU), to N, you must change it in MULTIPLE PLACES:
# 1. Set VLLM_TP_SIZE=N
# 2. Explicitly define the N device IDs for `CUDA_VISIBLE_DEVICES`
# 3. Specify these N device IDs in the deployment resources

networks:
  # copy-paste this block into any other services that use this vllm service.
  ai-backend:
    external: true

services:
  #====================  vLLM (OpenAI-compatible server)  ====================#
  vllm:
    # NB: `latest` very often does NOT support models that have been released
    #     within the last 7~14 days. So it's best you stick with `nightly`
    #image: vllm/vllm-openai:latest
    image: vllm/vllm-openai:nightly
    command: >
      --model ${VLLM_MODEL}
      --host 0.0.0.0 --port 8000
      --dtype auto
      --trust-remote-code
      --gpu-memory-utilization ${VLLM_GPU_UTIL:-0.90}
      --tensor-parallel-size ${VLLM_TP_SIZE:-1}
      --max-model-len ${VLLM_MAX_MODEL_LEN:-8192}
    #--enforce-eager
    # ^ this flag was necessary for a bizarre, atypical OOM with Qwen3.5-9B. kept for now.
    ipc: host
    environment:
      VLLM_DO_NOT_TRACK: ${VLLM_DO_NOT_TRACK:-1}
      HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
      #CUDA_VISIBLE_DEVICES: "0,1"
    volumes:
      - ${HF_CACHE_DIR:-${HOME}/.cache/hf-cache}:/root/.cache/huggingface
    ports:
      - "127.0.0.1:8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
              #device_ids: ["0", "1"]  # dual
    networks:
      - ai-backend
    restart: unless-stopped
